# Uncomment the next line to define a global platform for your project
  platform :ios, '14.0'

target 'Snapchat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snapchat
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'lottie-ios'
pod 'SkyFloatingLabelTextField'
end
